sudo: required
services:
  - docker

before_install:
  - docker build -t crkepler/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true crkepler/react-test npm test

after_success:
  #no need to specify the Dockerfile when already using the default one
  - docker build -t crkepler/multi-client ./client
  - docker build -t crkepler/multi-server ./server
  - docker build -t crkepler/multi-worker ./worker
  - docker build -t crkepler/multi-nginx ./nginx
  #login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push multi-client
  - docker push multi-server
  - docker push multi-worker
  - docker push multi-nginx

